package xap

import (
	"fmt"

	"github.com/Vidimuslabs/xap-go/canonical"
)

// Receipt is the verifiable execution receipt — the cryptographic proof
// structure generated by an enforcement point for every request, including
// denials (¶0050, ¶0088, ¶0097 as amended). The enforcement point signature is
// carried by the COSE_Sign1 envelope (see SignedReceipt), not this payload.
//
// A receipt is configured so an independent verifier can, from the receipt
// alone and reproduced inputs, recompute the runtime context digest, recompute
// per-constraint outcomes, validate signatures, check the evaluation timing
// bound, and check the chain link — without any access to enforcement point
// state (¶0017, ¶0095).
type Receipt struct {
	Version string `cbor:"v"`
	// ID is the receipt identifier (¶0097).
	ID string `cbor:"id"`
	// ArtifactID references the governing authority artifact (¶0050).
	ArtifactID string `cbor:"artifact_id"`
	// Action and Resource name the operation this receipt decided — ¶0097's
	// "reference to an execution request or operation". Without them a receipt
	// proves that a decision was made under ArtifactID against ContextDigest, but
	// not *what* was authorized, and an independent verifier cannot reproduce the
	// scope and boundary check of ¶0046 (pipeline step 2). Optional so that
	// pre-existing receipts still decode and so selective disclosure (¶0071,
	// ¶0079) can omit them; when present, Verify recomputes scope membership and
	// the boundary exclusion check against the governing MAT.
	Action   string `cbor:"action,omitempty"`
	Resource string `cbor:"resource,omitempty"`
	// Decision is the ternary execution control decision (¶0049).
	Decision string `cbor:"decision"`
	// Controls lists applied execution controls when Decision is
	// permit_with_controls (¶0049).
	Controls []string `cbor:"controls,omitempty"`
	// ContextDigest is the runtime context digest (¶0010). 32 bytes for SHA-256.
	ContextDigest []byte `cbor:"context_digest"`
	// RationaleCodes are signature-bound rationale/error codes (¶0084 addition).
	RationaleCodes []string `cbor:"rationale_codes,omitempty"`
	// ConstraintOutcomes records each constraint's binary outcome (¶0047).
	ConstraintOutcomes []ConstraintOutcome `cbor:"constraint_outcomes,omitempty"`
	// EvidenceRefs is the evidence reference set (¶0050, ¶0048).
	EvidenceRefs []EvidenceRef `cbor:"evidence_refs,omitempty"`
	// PolicyDigest is the constraint-compilation digest (¶0076).
	PolicyDigest []byte `cbor:"policy_digest,omitempty"`
	// Timing records evaluation start/completion/elapsed (¶0053).
	Timing Timing `cbor:"timing"`
	// PriorReceiptHash chains this receipt to the previous one (FIG. 11, ¶0063).
	// It carries the previous receipt's Digest — see Digest for why the link is
	// defined over the payload rather than the envelope.
	PriorReceiptHash []byte `cbor:"prior_hash,omitempty"`
	// ResourceStateDigest supports optimistic concurrency consistency checks
	// (¶0054).
	ResourceStateDigest []byte `cbor:"resource_state_digest,omitempty"`
	// Speculative flags a speculative evaluation pending confirmation (¶0078).
	Speculative bool `cbor:"speculative,omitempty"`
	// EnforcementPoint identifies the emitting enforcement point.
	EnforcementPoint string `cbor:"enforcement_point,omitempty"`

	// Commitment fields, present when a commitment object governs the session
	// (¶0084A, ¶0097 addition). A per-action receipt carries the digest of the
	// governing commitment and that action's compliance record.
	CommitmentDigest     []byte            `cbor:"commitment_digest,omitempty"`
	CommitmentCompliance *ActionCompliance `cbor:"commitment_compliance,omitempty"`
	// Provenance reconstructs a multi-agent commitment derivation chain from
	// receipts alone (¶0084A Commitment Provenance Field).
	Provenance *ProvenanceRef `cbor:"provenance,omitempty"`
}

// Timing records the evaluation window (¶0053). ElapsedMS from Start to
// Complete is checked against MaxMS to confirm evaluation completed within the
// authorized latency bound (¶0051, ¶0088).
type Timing struct {
	Start     string `cbor:"start"`
	Complete  string `cbor:"complete"`
	ElapsedMS int64  `cbor:"elapsed_ms"`
	// MaxMS is the maximum evaluation latency bound in force; 0 means unbounded.
	MaxMS int64 `cbor:"max_ms,omitempty"`
}

// EvidenceRef is one entry in the integrity evidence reference set (¶0048,
// ¶0050). It carries a category, a digest over the evidence, and the freshness
// outcome evaluated at execution time.
type EvidenceRef struct {
	Category string `cbor:"category"`
	Digest   []byte `cbor:"digest"`
	Fresh    bool   `cbor:"fresh"`
}

// ActionCompliance is the per-action commitment compliance record (¶0084A
// Commitment Compliance Field). It lets a verifier confirm, from the proof
// structure alone, that the proposed action was evaluated against the
// commitment object at the time of proposal.
type ActionCompliance struct {
	// Action is the proposed action descriptor evaluated.
	Action string `cbor:"action"`
	// CommitmentCheck: action was within the declared action set.
	CommitmentCheck bool `cbor:"commitment_check"`
	// ScopeCheck: action was within the execution scope.
	ScopeCheck bool `cbor:"scope_check"`
	// BoundaryCheck: action was within the permission boundary.
	BoundaryCheck bool `cbor:"boundary_check"`
	// ConstraintOutcome: applicable constraints were satisfied at proposal time.
	ConstraintOutcome bool `cbor:"constraint_outcome"`
	// Code is a rationale/error code when any check failed.
	Code string `cbor:"code,omitempty"`
}

// ProvenanceRef ties a receipt to a parent agent's authority artifact and
// commitment in a multi-agent derivation chain (¶0084A).
type ProvenanceRef struct {
	ParentArtifactID       string `cbor:"parent_artifact_id"`
	ParentCommitmentDigest []byte `cbor:"parent_commitment_digest"`
}

// SignedReceipt is a Receipt conveyed inside a COSE_Sign1 envelope.
type SignedReceipt struct {
	Envelope []byte
	Receipt  Receipt
	// SigningKID is the key id of the anchor that verified the envelope.
	SigningKID []byte
}

// Marshal returns the canonical CBOR payload of the receipt (¶0085).
func (r *Receipt) Marshal() ([]byte, error) {
	return canonical.Marshal(r)
}

// Digest returns the receipt digest: a digest over the canonical receipt
// payload. It is the chain-link value a successor records in its
// PriorReceiptHash (¶0063, FIG. 11), and it is the single definition of that
// link — the enforcement point computing it at issuance and a verifier
// recomputing it are calling the same function.
//
// It is deliberately a digest over the payload and not over the COSE envelope.
// The payload is what the signature covers and what canonicalization pins to
// one encoding; the envelope is neither, so envelope bytes cannot identify a
// receipt. The reasoning is set out in full above Verifier.Verify's chain-link
// step.
func (r *Receipt) Digest() ([]byte, error) {
	return canonical.DigestBytes(r)
}

// UnmarshalReceipt decodes a canonical CBOR payload into a Receipt.
func UnmarshalReceipt(payload []byte) (*Receipt, error) {
	var r Receipt
	if err := canonical.Unmarshal(payload, &r); err != nil {
		return nil, fmt.Errorf("decode receipt payload: %w", err)
	}
	return &r, nil
}
